export interface Verse {
  id: string;
  number: string;
  speaker?: string;
  text: string;
}

export interface Chapter {
  id: number;
  title: string;
  verses: Verse[];
}

export const chapters: Chapter[] = [
  {
    id: 1,
    title: "Instruction on Self-Realization",
    verses: [
      { id: "1.1", number: "1.1", speaker: "Janaka said:", text: "Master,\nhow is Knowledge to be achieved,\ndetachment acquired,\nliberation attained?" },
      { id: "1.2", number: "1.2", speaker: "Ashtavakra said:", text: "To be free,\nshun the experiences of the senses\nlike poison.\nTurn your attention to\nforgiveness, sincerity, kindness, simplicity, truth." },
      { id: "1.3", number: "1.3", speaker: "Ashtavakra said:", text: "You are not earth, water, fire or air.\nNor are you empty space.\nLiberation is to know yourself\nas Awareness alone—\nthe Witness of these." },
      { id: "1.4", number: "1.4", speaker: "Ashtavakra said:", text: "Abide in Awareness\nwith no illusion of person.\nYou will be instantly free and at peace." },
      { id: "1.5", number: "1.5", speaker: "Ashtavakra said:", text: "You have no caste or duties.\nYou are invisible, unattached, formless.\nYou are the Witness of all things.\nBe happy." },
      { id: "1.6", number: "1.6", speaker: "Ashtavakra said:", text: "Right and wrong, pleasure and pain,\nexist in mind only.\nThey are not your concern.\nYou neither do nor enjoy.\nYou are free." },
      { id: "1.7", number: "1.7", speaker: "Ashtavakra said:", text: "You are the Solitary Witness\nof All That Is,\nforever free.\nYour only bondage is not seeing This." },
      { id: "1.8", number: "1.8", speaker: "Ashtavakra said:", text: "The thought: \"I am the doer\"\nis the bite of a poisonous snake.\nTo know: \"I do nothing\"\nis the wisdom of faith.\nBe happy." },
      { id: "1.9", number: "1.9", speaker: "Ashtavakra said:", text: "A single understanding:\n\"I am the One Awareness,\"\nconsumes all suffering\nin the fire of an instant.\nBe happy." },
      { id: "1.10", number: "1.10", speaker: "Ashtavakra said:", text: "You are unbounded Awareness—\nBliss, Supreme Bliss—\nin which the universe appears\nlike the mirage of a snake in a rope.\nBe happy." },
      { id: "1.11", number: "1.11", speaker: "Ashtavakra said:", text: "It is true what they say:\n\"You are what you think.\"\nIf you think you are bound you are bound.\nIf you think you are free you are free." },
      { id: "1.12", number: "1.12", speaker: "Ashtavakra said:", text: "You are Self—the Solitary Witness.\nYou are perfect, all-pervading, One.\nYou are free, desireless, forever still.\nThe universe is but a seeming in You." },
      { id: "1.13", number: "1.13", speaker: "Ashtavakra said:", text: "Meditate on this: \"I am Awareness alone—Unity itself.\"\nGive up the idea that you are separate, a person,\nthat there is within and without." },
      { id: "1.14", number: "1.14", speaker: "Ashtavakra said:", text: "You have long been bound thinking:\n\"I am a person.\"\nLet the knowledge: \"I am Awareness alone\"\nbe the sword that frees you." },
      { id: "1.15", number: "1.15", speaker: "Ashtavakra said:", text: "You are now and forever\nfree, luminous, transparent, still.\nThe practice of meditation\nkeeps one in bondage." },
      { id: "1.16", number: "1.16", speaker: "Ashtavakra said:", text: "You are pure Consciousness—\nthe substance of the universe.\nThe universe exists within you.\nDon't be small-minded." },
      { id: "1.17", number: "1.17", speaker: "Ashtavakra said:", text: "You are unconditioned, changeless, formless.\nYou are solid, unfathomable, cool.\nDesire nothing.\nYou are Consciousness." },
      { id: "1.18", number: "1.18", speaker: "Ashtavakra said:", text: "That which has form is not real.\nOnly the formless is permanent.\nOnce this is known,\nyou will not return to illusion." },
      { id: "1.19", number: "1.19", speaker: "Ashtavakra said:", text: "Just as a mirror exists\nboth within and without\nthe image reflected,\nthe Supreme Self exists\nboth within and without the body." },
      { id: "1.20", number: "1.20", speaker: "Ashtavakra said:", text: "Just as the same space exists\nboth within and without a jar,\nthe timeless, all-pervasive One\nexists as Totality." },
    ]
  },
  {
    id: 2,
    title: "Joy of Self-Realization",
    verses: [
      { id: "2.1", number: "2.1", speaker: "Janaka said:", text: "I am now spotless and at peace—\nAwareness beyond Consciousness.\nAll this time\nI have been duped by illusion." },
      { id: "2.2", number: "2.2", speaker: "Janaka said:", text: "By this light alone\nthe body and the universe appear.\nI am Everything\nor Nothing." },
      { id: "2.3", number: "2.3", speaker: "Janaka said:", text: "Seeing there is no\nuniverse or body,\nby grace the Self is revealed." },
      { id: "2.4", number: "2.4", speaker: "Janaka said:", text: "As waves, foam and bubbles\nare not different from water,\nso the universe emanating from Self\nis not different from Self." },
      { id: "2.5", number: "2.5", speaker: "Janaka said:", text: "Look closely at cloth,\nyou see only threads.\nLook closely at creation,\nyou see only Self." },
      { id: "2.6", number: "2.6", speaker: "Janaka said:", text: "As sweetness\npervades sugarcane juice,\nI am the essence of creation." },
      { id: "2.7", number: "2.7", speaker: "Janaka said:", text: "Not seeing Self, the world is materialized.\nSeeing Self, the world is vanished.\nA rope is not a snake,\nbut can appear to be." },
      { id: "2.8", number: "2.8", speaker: "Janaka said:", text: "I am not other than Light.\nThe universe manifests\nat my glance." },
      { id: "2.9", number: "2.9", speaker: "Janaka said:", text: "The mirage of universe appears in me\nas silver appears in mother-of-pearl,\nas a snake appears in a rope,\nas water appears on a desert horizon." },
      { id: "2.10", number: "2.10", speaker: "Janaka said:", text: "As a pot returns to clay,\na wave to water,\na bracelet to gold,\nso will the universe return to Me." },
      { id: "2.11", number: "2.11", speaker: "Janaka said:", text: "I am wonderful indeed—\nbeyond adoration.\nI cannot decay nor ever die,\nthough God and all the universe\nshould perish to the last blade of grass." },
      { id: "2.12", number: "2.12", speaker: "Janaka said:", text: "I am wonderful indeed—\nbeyond adoration.\nEven with a body I am One.\nI neither come nor go.\nI am everywhere at once." },
      { id: "2.13", number: "2.13", speaker: "Janaka said:", text: "I am wonderful indeed—\nbeyond adoration.\nI am astounded at my powers.\nThe universe appears within me\nbut I do not touch it." },
      { id: "2.14", number: "2.14", speaker: "Janaka said:", text: "I am wonderful indeed—\nbeyond adoration.\nI am everything thought or spoken,\nand have nothing." },
      { id: "2.15", number: "2.15", speaker: "Janaka said:", text: "In Reality,\nknowledge, the knower, and the knowable\ndo not exist.\nI am the transparent Self\nin which through ignorance\nthey appear." },
      { id: "2.16", number: "2.16", speaker: "Janaka said:", text: "Looking at One and seeing many\nis the cause of all misery.\nThe only cure is to realize\nwhat is seen is not there.\nI am One—aware, blissful, immaculate." },
      { id: "2.17", number: "2.17", speaker: "Janaka said:", text: "I am unbounded Awareness.\nOnly in imagination do I have limits.\nReflecting on this,\nI abide in the Absolute." },
      { id: "2.18", number: "2.18", speaker: "Janaka said:", text: "I am neither free nor bound.\nThe illusion of such things\nhas fallen into disbelief.\nThough I contain creation,\nit has no substance." },
      { id: "2.19", number: "2.19", speaker: "Janaka said:", text: "Having seen for certain\nthat this universe and body\nis without form or substance,\nI am revealed as Awareness alone.\nImagination has no place here." },
      { id: "2.20", number: "2.20", speaker: "Janaka said:", text: "The body exists only in imagination,\nas do heaven and hell,\nbondage, freedom, fear.\nAre these my concern?\nI, who am pure Awareness?" },
      { id: "2.21", number: "2.21", speaker: "Janaka said:", text: "I see no differences or separation.\nEven the multitudes appear\nas a single formless desert.\nTo what should I cling?" },
      { id: "2.22", number: "2.22", speaker: "Janaka said:", text: "I am not the body.\nI do not have a body.\nI am Awareness, not a person.\nMy thirst for life bound me\nto a seeming of life." },
      { id: "2.23", number: "2.23", speaker: "Janaka said:", text: "In the limitless ocean of Myself\nthe winds of the mind\nroil the myriad waves of the world." },
      { id: "2.24", number: "2.24", speaker: "Janaka said:", text: "But when the wind subsides\nin the limitless ocean\nthe ark of personhood is swallowed up,\nalong with the universe it carries." },
      { id: "2.25", number: "2.25", speaker: "Janaka said:", text: "And how wonderful it is!\nIn the limitless ocean of Myself,\nwaves of beings\narise, collide, play for a time,\nthen disappear--as is their nature." },
    ]
  },
  {
    id: 3,
    title: "Test of Self-Realization",
    verses: [
      { id: "3.1", number: "3.1", speaker: "Ashtavakra said:", text: "Having realized yourself as One,\nbeing serene and indestructible,\nwhy do you desire wealth?" },
      { id: "3.2", number: "3.2", speaker: "Ashtavakra said:", text: "Just as imagining silver in mother-of-pearl,\ncauses greed to arise,\nso does ignorance of Self\ncause desire for illusion." },
      { id: "3.3", number: "3.3", speaker: "Ashtavakra said:", text: "Having realized yourself as That\nin which the waves of the world rise and fall,\nwhy do you run around in turmoil?" },
      { id: "3.4", number: "3.4", speaker: "Ashtavakra said:", text: "Having realized yourself as pure Awareness,\nas beautiful beyond description,\nhow can you remain a slave to lust?" },
      { id: "3.5", number: "3.5", speaker: "Ashtavakra said:", text: "It is strange\nthat in a sage who has realized\nSelf in All and All in Self\nthis sense of ownership should continue." },
      { id: "3.6", number: "3.6", speaker: "Ashtavakra said:", text: "Strange that one abiding in the Absolute,\nintent on freedom,\nshould be vulnerable to lust\nand weakened by amorous pastimes." },
      { id: "3.7", number: "3.7", speaker: "Ashtavakra said:", text: "Strange that knowing lust\nas an enemy of knowledge,\none so weak and nearing death\nshould still crave sensual pleasure." },
      { id: "3.8", number: "3.8", speaker: "Ashtavakra said:", text: "Strange that one who is unattached\nto the things of this world and the next,\nwho can discriminate between the transient and the timeless,\nwho yearns for freedom,\nshould yet fear the dissolution of the body." },
      { id: "3.9", number: "3.9", speaker: "Ashtavakra said:", text: "Whether acclaimed or tormented\nthe serene sage abides in the Self.\nHe is neither gratified nor angered." },
      { id: "3.10", number: "3.10", speaker: "Ashtavakra said:", text: "A great soul\nwitnesses his body's actions\nas if they were another's.\nHow can praise or blame disturb him?" },
      { id: "3.11", number: "3.11", speaker: "Ashtavakra said:", text: "Realizing the universe is illusion,\nhaving lost all curiosity,\nhow can one of steady mind fear death?" },
      { id: "3.12", number: "3.12", speaker: "Ashtavakra said:", text: "With whom can we compare\nthe great soul\nwho, content knowing Self,\nremains desireless in disappointment?" },
      { id: "3.13", number: "3.13", speaker: "Ashtavakra said:", text: "Why should a person of steady mind,\nwho sees the nothingness of objects,\nprefer one thing to another?" },
      { id: "3.14", number: "3.14", speaker: "Ashtavakra said:", text: "He who is unattached,\nuntouched by opposites,\nfree of desire,\nexperiences neither pleasure nor pain\nas events pass through." },
    ]
  },
  {
    id: 4,
    title: "Glorification of Self-Realization",
    verses: [
      { id: "4.1", number: "4.1", speaker: "Janaka said:", text: "Surely one who knows Self,\nthough he plays the game of life,\ndiffers greatly from the world's\nbewildered burdened beasts." },
      { id: "4.2", number: "4.2", speaker: "Janaka said:", text: "Truly the yogi feels no elation,\nthough he abides in the exalted state\nyearned for by Indra and all the\ndiscontented gods." },
      { id: "4.3", number: "4.3", speaker: "Janaka said:", text: "Surely one who knows That\nis not touched by virtue or vice,\njust as space is not touched by smoke,\nthough it seems to be." },
      { id: "4.4", number: "4.4", speaker: "Janaka said:", text: "Who can prevent the great soul,\nwho knows the universe as Self,\nfrom living life as it comes?" },
      { id: "4.5", number: "4.5", speaker: "Janaka said:", text: "Of the four kinds of beings,\nfrom Brahma to a blade of grass,\nonly the sage can renounce\naversion and desire." },
      { id: "4.6", number: "4.6", speaker: "Janaka said:", text: "Rare is he who knows himself\nas One with no other—\nthe Lord of the Universe.\nHe acts as he knows\nand is never afraid." },
    ]
  },
  {
    id: 5,
    title: "Four Ways to Dissolution",
    verses: [
      { id: "5.1", number: "5.1", speaker: "Ashtavakra said:", text: "You are immaculate,\ntouched by nothing.\nWhat is there to renounce?\nThe mind is complex—let it go.\nKnow the peace of dissolution." },
      { id: "5.2", number: "5.2", speaker: "Ashtavakra said:", text: "The universe arises from you\nlike foam from the sea.\nKnow yourself as One.\nEnter the peace of dissolution." },
      { id: "5.3", number: "5.3", speaker: "Ashtavakra said:", text: "Like an imagined snake in a rope\nthe universe appears to exist\nin the immaculate Self\nbut does not.\nSeeing this you know: \"There is nothing to dissolve.\"" },
      { id: "5.4", number: "5.4", speaker: "Ashtavakra said:", text: "You are perfect, changeless,\nthrough misery and happiness,\nhope and despair,\nlife and death.\nThis is the state of dissolution." },
    ]
  },
  {
    id: 6,
    title: "The Higher Knowledge",
    verses: [
      { id: "6.1", number: "6.1", speaker: "Janaka said:", text: "I am infinite space;\nthe universe is a jar.\nThis I know.\nNo need to renounce, accept or destroy." },
      { id: "6.2", number: "6.2", speaker: "Janaka said:", text: "I am a shoreless ocean;\nthe universe makes waves.\nThis I know.\nNo need to renounce, accept or destroy." },
      { id: "6.3", number: "6.3", speaker: "Janaka said:", text: "I am mother-of-pearl;\nthe universe is the illusion of silver.\nThis I know.\nNo need to renounce, accept or destroy." },
      { id: "6.4", number: "6.4", speaker: "Janaka said:", text: "I am in all beings;\nall beings are in me.\nThis I know.\nNo need to renounce, accept or destroy." },
    ]
  },
  {
    id: 7,
    title: "Nature of Self-Realization",
    verses: [
      { id: "7.1", number: "7.1", speaker: "Janaka said:", text: "In me, the shoreless ocean,\nthe ark of universe\ndrifts here and there\non the winds of its nature.\nI am not impatient." },
      { id: "7.2", number: "7.2", speaker: "Janaka said:", text: "In me, the shoreless ocean,\nlet the waves of the universe\nrise and fall as they will.\nI am neither enhanced nor diminished." },
      { id: "7.3", number: "7.3", speaker: "Janaka said:", text: "In me, the shoreless ocean,\nthe universe is imagined.\nI am still and formless.\nIn this alone I abide." },
      { id: "7.4", number: "7.4", speaker: "Janaka said:", text: "The Self is not in objects,\nnor are objects in the pure and infinite Self.\nThe Self is tranquil,\nfree of attachment and desire.\nIn this alone I abide." },
      { id: "7.5", number: "7.5", speaker: "Janaka said:", text: "I am Awareness alone.\nThe world is passing show.\nHow can thoughts arise\nof acceptance or rejection?\nAnd where?" },
    ]
  },
  {
    id: 8,
    title: "Bondage and Liberation",
    verses: [
      { id: "8.1", number: "8.1", speaker: "Ashtavakra said:", text: "When the mind desires or grieves things,\naccepts or rejects things,\nis pleased or displeased by things--\nthis is bondage." },
      { id: "8.2", number: "8.2", speaker: "Ashtavakra said:", text: "When the mind does not\ndesire or grieve,\naccept or reject,\nbecome pleased or displeased,\nliberation is at hand." },
      { id: "8.3", number: "8.3", speaker: "Ashtavakra said:", text: "If the mind is attached to any experience,\nthis is bondage.\nWhen the mind is detached from all experience,\nthis is liberation." },
      { id: "8.4", number: "8.4", speaker: "Ashtavakra said:", text: "When there is no \"I\"\nthere is only liberation.\nWhen \"I\" appears\nbondage appears with it.\nKnowing this,\nit is effortless to refrain\nfrom accepting and rejecting." },
    ]
  },
  {
    id: 9,
    title: "Detachment",
    verses: [
      { id: "9.1", number: "9.1", speaker: "Ashtavakra said:", text: "Opposing forces,\nduties done and left undone—\nwhen does it end\nand for whom?\nConsidering this, be ever desireless,\nlet go of all things,\nand to the world turn an indifferent eye." },
      { id: "9.2", number: "9.2", speaker: "Ashtavakra said:", text: "Rare and blessed is one\nwhose desire to live,\nto enjoy and to know,\nhas been extinguished by observing\nthe ways of men." },
      { id: "9.3", number: "9.3", speaker: "Ashtavakra said:", text: "Seeing all things as threefold suffering,\nthe sage becomes still.\nInsubstantial, transient, contemptible--\nthe world is fit only for rejection." },
      { id: "9.4", number: "9.4", speaker: "Ashtavakra said:", text: "Was there an age or time\nmen existed without opposites?\nLeave the opposites behind.\nBe content with what comes.\nPerfection." },
      { id: "9.5", number: "9.5", speaker: "Ashtavakra said:", text: "The greatest seers, saints and yogis\nagree on very little.\nSeeing this,\nwho could not be indifferent to knowledge\nand become still?" },
      { id: "9.6", number: "9.6", speaker: "Ashtavakra said:", text: "One who\nthrough worldly indifference,\nthrough serenity and reason,\nsees his true nature and escapes illusion—\nis he not a true teacher?" },
      { id: "9.7", number: "9.7", speaker: "Ashtavakra said:", text: "In the myriad forms of the universe\nsee the primal element alone.\nYou will be instantly free,\nand abide in Self." },
      { id: "9.8", number: "9.8", speaker: "Ashtavakra said:", text: "Desire creates the world--renounce it.\nRenounce desires\nand you renounce the world.\nNow you may live as you are." },
    ]
  },
  {
    id: 10,
    title: "Quietude",
    verses: [
      { id: "10.1", number: "10.1", speaker: "Ashtavakra said:", text: "Give up desire,\nwhich is the enemy.\nGive up prosperity,\nwhich is born of mischief and good works.\nBe indifferent." },
      { id: "10.2", number: "10.2", speaker: "Ashtavakra said:", text: "Look upon\nfriends, lands, wealth, houses, wives, gifts--\nand all apparent good fortune--\nas a passing show,\nas a dream lasting three to five days." },
      { id: "10.3", number: "10.3", speaker: "Ashtavakra said:", text: "Where there is desire, there is the world.\nBe firm in non-attachment.\nBe free of desire.\nBe happy." },
      { id: "10.4", number: "10.4", speaker: "Ashtavakra said:", text: "Bondage and desire are the same.\nDestroy desire and be free.\nOnly by detaching from the world\ndoes one joyfully realize Self." },
      { id: "10.5", number: "10.5", speaker: "Ashtavakra said:", text: "You are One—\nAwareness itself.\nThe universe is neither aware\nnor does it exist.\nEven ignorance is unreal.\nWhat is left to know?" },
      { id: "10.6", number: "10.6", speaker: "Ashtavakra said:", text: "Attached as you have been to\nkingdoms, sons, wives, bodies, pleasures—\nlife after life—\nstill they are now lost forever." },
      { id: "10.7", number: "10.7", speaker: "Ashtavakra said:", text: "Prosperity, pleasure, pious deeds...\nEnough!\nIn the dreary forest of the world\nthe mind finds no rest." },
      { id: "10.8", number: "10.8", speaker: "Ashtavakra said:", text: "For how many lifetimes\nhave you done hard and painful labor\nwith body, mind and speech?\nIt is time to stop." },
    ]
  },
  {
    id: 11,
    title: "Wisdom",
    verses: [
      { id: "11.1", number: "11.1", speaker: "Ashtavakra said:", text: "Existence, non-existence, change--\nthis is the nature of things.\nRealizing this,\nstillness, serenity and bliss\nnaturally follow." },
      { id: "11.2", number: "11.2", speaker: "Ashtavakra said:", text: "One who knows for certain that\n\"Self creates All and is alone\"\nbecomes still, desireless, unattached." },
      { id: "11.3", number: "11.3", speaker: "Ashtavakra said:", text: "One who knows for certain\nthat adversity and success\ncome and go in obedience to destiny\nbecomes content.\nHe neither desires nor grieves." },
      { id: "11.4", number: "11.4", speaker: "Ashtavakra said:", text: "One who knows for certain\nthat birth and death, happiness and misery,\ncome and go in obedience to destiny\nsees nothing to accomplish.\nHe engages in non-action,\nand in action remains unattached." },
      { id: "11.5", number: "11.5", speaker: "Ashtavakra said:", text: "One who has realized\nthat only by caring\nis misery caused in the world\nbecomes free, happy, serene, desireless." },
      { id: "11.6", number: "11.6", speaker: "Ashtavakra said:", text: "\"I am not the body, nor is the body my possession—\nI am Awareness itself.\"\nOne who realizes this for certain\nhas no memory of things done or left undone.\nThere is only the Absolute." },
      { id: "11.7", number: "11.7", speaker: "Ashtavakra said:", text: "\"From Brahma to the last blade of grass--\nI alone exist.\"\nOne who knows this for certain\nbecomes immaculate, serene, unconflicted.\nAttainment has no meaning." },
      { id: "11.8", number: "11.8", speaker: "Ashtavakra said:", text: "One who knows for certain\nthat this manifold and wonderful universe\nis nothing\nbecomes desireless Awareness\nand abides in the stillness of No-thing." },
    ]
  },
  {
    id: 12,
    title: "Abiding in the Self",
    verses: [
      { id: "12.1", number: "12.1", speaker: "Janaka said:", text: "Becoming first intolerant of action,\nthen of excessive speech,\nthen of thought itself,\nI come to be here." },
      { id: "12.2", number: "12.2", speaker: "Janaka said:", text: "Neither sounds nor other sense perceptions\nattract my attention.\nEven the Self is unperceived.\nThe mind is free, undistracted, one-pointed.\nAnd here I am." },
      { id: "12.3", number: "12.3", speaker: "Janaka said:", text: "Effort is required\nto concentrate a distracted mind\nsuperimposed with illusion.\nKnowing this, I remain here." },
      { id: "12.4", number: "12.4", speaker: "Janaka said:", text: "Nothing to reject,\nnothing to accept.\nNo joy, no sorrow.\nLord God I am here." },
      { id: "12.5", number: "12.5", speaker: "Janaka said:", text: "The four stages of life,\nlife without stages,\nmeditation, renunciation, objects of mind—\nnothing but distractions.\nI am forever here." },
      { id: "12.6", number: "12.6", speaker: "Janaka said:", text: "Doing and not-doing\nboth arise from ignorance.\nI know this.\nAnd I am here." },
      { id: "12.7", number: "12.7", speaker: "Janaka said:", text: "Thinking of the unthinkable One\nunavoidably conjures thought.\nI choose no-thought\nand remain here." },
      { id: "12.8", number: "12.8", speaker: "Janaka said:", text: "Blessed is he\nwho attains this by effort.\nBlessed is he\nwho is such by nature." },
    ]
  },
  {
    id: 13,
    title: "Happiness",
    verses: [
      { id: "13.1", number: "13.1", speaker: "Janaka said:", text: "The tranquil state\nof knowing Self alone is rare—\neven among those who own but a loincloth.\nI therefore neither renounce nor accept\nand am happy." },
      { id: "13.2", number: "13.2", speaker: "Janaka said:", text: "The body is strained by practices.\nThe tongue tires of scripture.\nThe mind numbs with meditation.\nDetached from all this,\nI live as I am." },
      { id: "13.3", number: "13.3", speaker: "Janaka said:", text: "Realizing that nothing is done,\nI do what comes\nand am happy." },
      { id: "13.4", number: "13.4", speaker: "Janaka said:", text: "Yogis who preach\neither effort or non-effort\nare still attached to the body.\nI neither dissociate nor associate\nwith any of that\nand am happy." },
      { id: "13.5", number: "13.5", speaker: "Janaka said:", text: "I have nothing to gain or lose\nby standing, walking or sitting down.\nSo whether I stand, walk or sit\nI am happy." },
      { id: "13.6", number: "13.6", speaker: "Janaka said:", text: "I do not lose by sleeping\nnor attain by effort.\nNot thinking in terms of loss or gain\nI am happy." },
      { id: "13.7", number: "13.7", speaker: "Janaka said:", text: "Pleasure and pain fluctuate\nand are inconsistent.\nWithout good or bad\nI live happily." },
    ]
  },
  {
    id: 14,
    title: "Tranquility",
    verses: [
      { id: "14.1", number: "14.1", speaker: "Janaka said:", text: "Though appearing asleep like other men,\none whose interest in the world is exhausted,\nwhose mind has been emptied,\nwho thinks only by inadvertence,\nis in Reality awake." },
      { id: "14.2", number: "14.2", speaker: "Janaka said:", text: "When desire has melted,\nhow can there be wealth,\nor friends, or the seduction of senses?\nWhat use is scripture and knowledge?" },
      { id: "14.3", number: "14.3", speaker: "Janaka said:", text: "I have realized the Supreme Self,\nthe Witness, the One.\nI am indifferent\nto bondage and freedom.\nI have no need for liberation." },
      { id: "14.4", number: "14.4", speaker: "Janaka said:", text: "The inner condition\nof one who is devoid of doubt\nyet moves among creatures of illusion\ncan only be known by those like him." },
    ]
  },
  {
    id: 15,
    title: "Knowledge of the Self",
    verses: [
      { id: "15.1", number: "15.1", speaker: "Ashtavakra said:", text: "A man of open intuition\nmay realize the Self upon\nhearing a casual instruction,\nwhile a man of cluttered intellect\ninquires bewildered for a lifetime." },
      { id: "15.2", number: "15.2", speaker: "Ashtavakra said:", text: "Aversion to the world's offerings is liberation.\nAttraction to the world's offerings\nis the suffering of bondage.\nThis is the truth.\nNow do as you please." },
      { id: "15.3", number: "15.3", speaker: "Ashtavakra said:", text: "This knowledge of Truth\nturns an eloquent, wise and active man\nmute, empty and inert.\nLovers of the world therefore shun it." },
      { id: "15.4", number: "15.4", speaker: "Ashtavakra said:", text: "You are not the body.\nYou do not have a body.\nYou neither do nor enjoy.\nYou are Awareness only--the timeless Witness.\nYou are free.\nGo in happiness." },
      { id: "15.5", number: "15.5", speaker: "Ashtavakra said:", text: "Attachment and aversion\nare attributes of the mind.\nYou are not the mind.\nYou are Consciousness itself--\nchangeless, undivided, free.\nGo in happiness." },
      { id: "15.6", number: "15.6", speaker: "Ashtavakra said:", text: "Realize Self in All and All in Self.\nBe free of personal identity\nand the sense of \"mine.\"\nBe happy." },
      { id: "15.7", number: "15.7", speaker: "Ashtavakra said:", text: "You are That in which the universe appears\nlike waves appearing in the ocean.\nYou are Consciousness itself.\nNo need to worry." },
      { id: "15.8", number: "15.8", speaker: "Ashtavakra said:", text: "Have faith, my son, have faith.\nYou are Awareness alone,\nthe Self, the One.\nYou are the Lord of Nature." },
      { id: "15.9", number: "15.9", speaker: "Ashtavakra said:", text: "The body is made of worldly stuff.\nIt comes, it lingers, it goes.\nThe Self neither comes nor goes,\nyet remains.\nWhy mourn the body?" },
      { id: "15.10", number: "15.10", speaker: "Ashtavakra said:", text: "If the body lasts until the end of time\nor perishes today—\nis there gain or loss for you?\nYou who are Awareness?" },
      { id: "15.11", number: "15.11", speaker: "Ashtavakra said:", text: "Let the waves of the universe\nrise and fall as they will.\nYou have nothing to gain or lose.\nYou are the ocean." },
      { id: "15.12", number: "15.12", speaker: "Ashtavakra said:", text: "You are the substance of Consciousness.\nThe world is You.\nWho is it that thinks\nhe can accept or reject it?\nAnd where does he stand?" },
      { id: "15.13", number: "15.13", speaker: "Ashtavakra said:", text: "In you who are One—\nimmaculate, still Awareness—\nfrom where can birth, action\nor a separate person arise?" },
      { id: "15.14", number: "15.14", speaker: "Ashtavakra said:", text: "Whatever you perceive\nis You and You alone.\nHow can bracelets, armlets and anklets\nbe other than the gold they are made of?" },
      { id: "15.15", number: "15.15", speaker: "Ashtavakra said:", text: "Leave behind such distinctions\nas \"I am He, the Self,\"\nand \"I am not this.\"\nConsider everything Self.\nBe desireless.\nBe happy." },
      { id: "15.16", number: "15.16", speaker: "Ashtavakra said:", text: "Your ignorance alone\ncreates the universe.\nIn reality One alone exists.\nThere is no person or god\nother than You." },
      { id: "15.17", number: "15.17", speaker: "Ashtavakra said:", text: "One who knows for certain\nthat the universe is illusion," },
    ]
  },
  {
    id: 16,
    title: "Effort and No-Effort",
    verses: [
      { id: "16.1", number: "16.1", speaker: "Ashtavakra said:", text: "The yogi who is full of the sense of \"I am the doer\"\nis far from freedom.\nHe has not found peace." },
      { id: "16.2", number: "16.2", speaker: "Ashtavakra said:", text: "Effort to concentrate a scattered mind\nas if gathering straws,\nwill result in a scattered mind." },
      { id: "16.3", number: "16.3", speaker: "Ashtavakra said:", text: "He who holds to \"I am\"\nmissing entirely what is\nwill never arrive at freedom." },
      { id: "16.4", number: "16.4", speaker: "Ashtavakra said:", text: "Knowing yourself as neither the doer\nnor the enjoyer,\nalthough the world may see you as acting,\nremain unshaken." },
      { id: "16.5", number: "16.5", speaker: "Ashtavakra said:", text: "Even hearing the highest Truth,\nthe mind tethered to desires\ncannot find tranquility." },
      { id: "16.6", number: "16.6", speaker: "Ashtavakra said:", text: "Discrimination and detachment,\npeace, forbearance--\nfrom these three naturally springs\ndeliberation." },
      { id: "16.7", number: "16.7", speaker: "Ashtavakra said:", text: "One who tastes this elixir,\neven for an instant,\nfinds peace." },
      { id: "16.8", number: "16.8", speaker: "Ashtavakra said:", text: "When the mind becomes free\nof the grip of sense objects,\nknowledge naturally springs forth,\nlike light from fire." },
    ]
  },
  {
    id: 17,
    title: "The Nature of the Free",
    verses: [
      { id: "17.1", number: "17.1", speaker: "Ashtavakra said:", text: "The wise one\nwho has realized the truth\nbehaves as he has done before,\nthough all conditioning has dropped away." },
      { id: "17.2", number: "17.2", speaker: "Ashtavakra said:", text: "The wise one sits\nthough others run about.\nHe speaks\nthough others are silent." },
      { id: "17.3", number: "17.3", speaker: "Ashtavakra said:", text: "He walks about\nthough others sit.\nHe associates with all,\nyet is free of identification." },
      { id: "17.4", number: "17.4", speaker: "Ashtavakra said:", text: "To eat, to sleep, to defend the body\nwhen it is attacked--\nthese are done out of habit." },
      { id: "17.5", number: "17.5", speaker: "Ashtavakra said:", text: "Even though he may listen,\nthe wise one hears nothing.\nEven though he may look,\nhe sees nothing." },
      { id: "17.6", number: "17.6", speaker: "Ashtavakra said:", text: "His senses are like flowers\nwithout fragrance,\nfor all sense objects are nil\nwithin the Self." },
      { id: "17.7", number: "17.7", speaker: "Ashtavakra said:", text: "In him exists neither pain nor disease,\nneither pleasure nor joy.\nHow can impurity touch\nthe one free from the three gunas?" },
      { id: "17.8", number: "17.8", speaker: "Ashtavakra said:", text: "Untroubled and free,\nhe neither desires his life\nnor shuns death.\nHis focus is on freedom alone." },
    ]
  },
  {
    id: 18,
    title: "Peace",
    verses: [
      { id: "18.1", number: "18.1", speaker: "Ashtavakra said:", text: "Praise That,\nwhich is Bliss itself,\nwhich is by nature stillness and light,\nand which by Its knowing\nreveals the world as a dream." },
      { id: "18.2", number: "18.2", speaker: "Ashtavakra said:", text: "One may enjoy the abundant pleasures of the world,\nbut will never be happy\nuntil giving them up." },
      { id: "18.3", number: "18.3", speaker: "Ashtavakra said:", text: "How can one whose innermost heart\nhas been scorched by the sun of sorrow\nthat comes from duty\nbe happy until the sweet rain\nof torrential stillness?" },
      { id: "18.4", number: "18.4", speaker: "Ashtavakra said:", text: "The universe is but a thought\nin Consciousness.\nIn Reality it is nothing.\nOne who sees the true nature\nof existence and non-existence\nnever ceases to exist." },
      { id: "18.5", number: "18.5", speaker: "Ashtavakra said:", text: "The Self—which is\nabsolute, effortless, timeless, immaculate—\nis without limits\nand at no distance from you.\nYou are forever It." },
      { id: "18.6", number: "18.6", speaker: "Ashtavakra said:", text: "For those whose vision becomes unclouded,\nillusion evaporates\nand the Self becomes known.\nAll sorrow is instantly dispelled." },
      { id: "18.7", number: "18.7", speaker: "Ashtavakra said:", text: "Seeing everything is imagination,\nknowing the Self as timelessly free,\nthe sage lives as a child." },
      { id: "18.8", number: "18.8", speaker: "Ashtavakra said:", text: "Knowing himself as Absolute,\nknowing existence and non-existence\nto be imagination only,\nwhat is there for the desireless one\nto learn, say or do?" },
      { id: "18.9", number: "18.9", speaker: "Ashtavakra said:", text: "Knowing for certain that all is Self,\nthe sage has no trace of thoughts\nsuch as \"I am this\" or \"I am not that.\"" },
      { id: "18.10", number: "18.10", speaker: "Ashtavakra said:", text: "The yogi who finds stillness\nis neither distracted nor focused.\nHe knows neither pleasure nor pain.\nIgnorance dispelled,\nhe is free of knowing." },
      { id: "18.11", number: "18.11", speaker: "Ashtavakra said:", text: "Heaven or poverty,\ngain or loss,\nsociety or solitude,\nto the yogi free of conditioning\nthere is no difference." },
      { id: "18.12", number: "18.12", speaker: "Ashtavakra said:", text: "Religious merit,\nsensory pleasure,\nworldly prosperity,\ndiscrimination between this and that—\nthese have no significance\nto the yogi free of opposites\nsuch as \"I do this\"\nand \"this I do not.\"" },
      { id: "18.13", number: "18.13", speaker: "Ashtavakra said:", text: "The yogi who is liberated while living\nhas no duties in this world,\nno attachments in his heart.\nHis life proceeds without him." },
      { id: "18.14", number: "18.14", speaker: "Ashtavakra said:", text: "For the great soul\nwho abides beyond desire,\nwhere is illusion?\nWhere is the universe?\nWhere is meditation on That?\nWhere even is liberation from them?" },
      { id: "18.15", number: "18.15", speaker: "Ashtavakra said:", text: "He who sees the world\nmay try to renounce it.\nBut what can the desireless one do?\nHe sees there is nothing to see." },
      { id: "18.16", number: "18.16", speaker: "Ashtavakra said:", text: "He who has seen the Supreme Brahma\nthinks, \"I am Brahma.\"\nBut he who has transcended all thought,\nwhat can he think?\nHe knows no other than Self." },
      { id: "18.17", number: "18.17", speaker: "Ashtavakra said:", text: "He achieves self-control\nwho sees his own distraction.\nBut the great soul is not distracted.\nHe has nothing to achieve.\nHe has nothing to do." },
      { id: "18.18", number: "18.18", speaker: "Ashtavakra said:", text: "The man of Knowledge\nmay live as an ordinary man,\nbut he is not.\nHe sees he is neither\nfocused nor distracted,\nand finds no fault with himself." },
      { id: "18.19", number: "18.19", speaker: "Ashtavakra said:", text: "He who is beyond existence and non-existence—\nwho is wise, satisfied, free of desire—\ndoes nothing,\nthough the world may see him in motion." },
      { id: "18.20", number: "18.20", speaker: "Ashtavakra said:", text: "The wise one\nis not troubled by action or inactivity.\nHe lives happily,\ndoing whatever gets done." },
      { id: "18.21", number: "18.21", speaker: "Ashtavakra said:", text: "Like a leaf in the wind\nthe liberated one\nis untethered from life—\ndesireless, independent, free." },
      { id: "18.22", number: "18.22", speaker: "Ashtavakra said:", text: "For one who has transcended the world\nthere is no joy or sorrow.\nWith a stilled mind,\nhe lives on with no body." },
      { id: "18.23", number: "18.23", speaker: "Ashtavakra said:", text: "One who knows Self,\nwhose mind is serene and spotless,\ndoes not desire to give up anything,\nnor does he miss what is not there." },
      { id: "18.24", number: "18.24", speaker: "Ashtavakra said:", text: "His mind being in a natural state\nof emptiness,\nthe wise one knows nothing\nof honor and dishonor.\nHe does what comes to be done." },
      { id: "18.25", number: "18.25", speaker: "Ashtavakra said:", text: "One who acts knowing\n\"This is done by the body, not by I, pure Self,\"\nindeed does nothing—\nno matter how much acting takes place." },
      { id: "18.26", number: "18.26", speaker: "Ashtavakra said:", text: "The liberated one\nacts without claiming to be acting,\nbut he is no fool.\nHe is blessed and happy\neven though in the world." },
      { id: "18.27", number: "18.27", speaker: "Ashtavakra said:", text: "Having had enough\nof the endless workings of the mind,\nthe wise one comes to rest.\nHe neither thinks, nor knows,\nnor hears, nor sees." },
      { id: "18.28", number: "18.28", speaker: "Ashtavakra said:", text: "Beyond stillness,\nbeyond distraction,\nthe great soul thinks nothing\nof liberation or bondage.\nHaving seen the universe is void—\neven though it seems to exist—\nhe is God." },
      { id: "18.29", number: "18.29", speaker: "Ashtavakra said:", text: "He who believes he is a person\nis constantly acting,\neven when the body is at rest.\nThe sage knows he is not a person,\nand therefore does nothing,\neven when the body is in motion." },
      { id: "18.30", number: "18.30", speaker: "Ashtavakra said:", text: "The mind of the liberated one\nis neither troubled nor pleased.\nIt is actionless, motionless, desireless\nand free of doubt." },
      { id: "18.31", number: "18.31", speaker: "Ashtavakra said:", text: "The liberated one\ndoes not exert effort\nto meditate or act.\nAction and meditation just happen." },
      { id: "18.32", number: "18.32", speaker: "Ashtavakra said:", text: "Hearing ultimate Truth,\nthe dull-witted man is bewildered.\nThe wise man hearing Truth\nretreats within and appears\ndull-witted." },
      { id: "18.33", number: "18.33", speaker: "Ashtavakra said:", text: "The ignorant practice\nmeditation and no-thought.\nThe wise,\nlike men in deep sleep,\ndo nothing." },
      { id: "18.34", number: "18.34", speaker: "Ashtavakra said:", text: "The ignorant man finds no peace\neither by effort or non-effort.\nThe wise man\nby Truth alone is stilled." },
      { id: "18.35", number: "18.35", speaker: "Ashtavakra said:", text: "Though they are by nature Self alone,\npure intelligence, love and perfection;\nthough they transcend the universe\nand are clearness itself,\nmen of the world will not see this\nthrough meditation and practices." },
      { id: "18.36", number: "18.36", speaker: "Ashtavakra said:", text: "The ignorant man\nwill never be liberated\nby his repetitious practices.\nBlessed is he who\nby simple understanding\nenters timeless freedom." },
      { id: "18.37", number: "18.37", speaker: "Ashtavakra said:", text: "Because he desires to know God,\nthe ignorant man can never become That.\nThe wise man is God\nbecause he is free of desire\nand knows nothing." },
      { id: "18.38", number: "18.38", speaker: "Ashtavakra said:", text: "Unable to stand steady\nand eager for salvation,\nthe ignorant perpetuate\nthe illusion of world.\nSeeing the world\nas the source of all misery,\nthe wise cut it off at the root." },
      { id: "18.39", number: "18.39", speaker: "Ashtavakra said:", text: "The fool thinks peace comes\nby controlling the mind.\nHe will never attain it.\nThe wise one knows Truth,\nand is stillness itself." },
      { id: "18.40", number: "18.40", speaker: "Ashtavakra said:", text: "For he who thinks knowledge\nis things and ideas\nhow can there be Self-knowledge?\nThe wise do not see separate things—\nonly the timeless Self." },
      { id: "18.41", number: "18.41", speaker: "Ashtavakra said:", text: "The fool tries to control the mind\nwith the mind—what folly!\nThe wise one delights in Self alone.\nThere is no mind to master." },
      { id: "18.42", number: "18.42", speaker: "Ashtavakra said:", text: "Some believe in existence;\nothers believe nothing exists.\nRare is the one who believes nothing\nand is never confused." },
      { id: "18.43", number: "18.43", speaker: "Ashtavakra said:", text: "Weak intellectuals may believe\nthe Self is One without other.\nBut being mired in illusion\nthey do not actually know Self,\nso live out their lives in misery." },
      { id: "18.44", number: "18.44", speaker: "Ashtavakra said:", text: "The mind of one seeking liberation\ndepends on things for perception.\nThe mind of the liberated one\nperceives no-thing\nand is free of desire." },
      { id: "18.45", number: "18.45", speaker: "Ashtavakra said:", text: "Timid men fear sensory experience\nmuch as they do tigers.\nThey seek refuge in caves\nand try to un-think the world." },
      { id: "18.46", number: "18.46", speaker: "Ashtavakra said:", text: "Sensory experiences are like elephants who,\nupon encountering a desireless man,\nsee him as a lion.\nThey immediately turn on their heels,\nor if unable to escape,\nstay on to flatter and serve him." },
      { id: "18.47", number: "18.47", speaker: "Ashtavakra said:", text: "A man with no doubts,\nwho knows only Self,\nhas no need of practice\nor liberation.\nSeeing, hearing, touching, smelling, eating—\nhe lives as he is, happily." },
      { id: "18.48", number: "18.48", speaker: "Ashtavakra said:", text: "One whose mind is emptied and unconflicted\nby the mere hearing of Truth\nsees nothing to do,\nnothing to avoid,\nnothing to warrant his indifference." },
      { id: "18.49", number: "18.49", speaker: "Ashtavakra said:", text: "The sage does whatever\nappears to be done\nwithout thinking of good or bad.\nHis actions are those of a child." },
      { id: "18.50", number: "18.50", speaker: "Ashtavakra said:", text: "Depending on nothing,\none finds happiness.\nDepending on nothing,\none attains the Supreme.\nDepending on nothing,\none passes through tranquility\nto One Self." },
      { id: "18.51", number: "18.51", speaker: "Ashtavakra said:", text: "When one realizes\nhe is neither the actor\nnor the one who watches,\nthe mind-storm is stilled." },
      { id: "18.52", number: "18.52", speaker: "Ashtavakra said:", text: "The actions of the sage,\nfree of pretence and motive,\nshine like clear light.\nNot so those of the deluded seeker\nwho affects a peaceful demeanor\nwhile remaining firmly attached." },
      { id: "18.53", number: "18.53", speaker: "Ashtavakra said:", text: "Unbounded, unfettered,\nuntethered from the projections of mind,\nthe wise are free to play and enjoy,\nor retire to mountain caves." },
      { id: "18.54", number: "18.54", speaker: "Ashtavakra said:", text: "Whether honoring a spiritual scholar,\na god, or holy shrine;\nwhether seeing a desirable woman,\na king, or beloved friend—\nthe heart of the sage\nis unmoved." },
      { id: "18.55", number: "18.55", speaker: "Ashtavakra said:", text: "Though his servants, sons,\nwives, daughters, grandchildren\nand all his wealth surround him,\nthe liberated one,\nfree of attachment,\nremains apart." },
      { id: "18.56", number: "18.56", speaker: "Ashtavakra said:", text: "To one in whom desire,\naversion and confusion are extinct,\nwhat are children,\nwhat is a wife,\nwhat is loss,\nwhat is gain?" },
      { id: "18.57", number: "18.57", speaker: "Ashtavakra said:", text: "The sage,\nfree of ego and false knowing,\nlives happily in this world\nwithout any purpose." },
      { id: "18.58", number: "18.58", speaker: "Ashtavakra said:", text: "One free of the sense of \"I\" and \"mine\"\nacts as he will.\nHe has no sense of committing sin\nor performing good deeds." },
      { id: "18.59", number: "18.59", speaker: "Ashtavakra said:", text: "The yogi free of becoming\nsees the universe as void.\nHe dwells in this world\nwithout body consciousness." },
      { id: "18.60", number: "18.60", speaker: "Ashtavakra said:", text: "The great soul\nfree of desire,\nfree of aversion,\nfree of fear,\nenjoys the bliss of Brahman." },
      { id: "18.61", number: "18.61", speaker: "Ashtavakra said:", text: "In the liberated one,\nwhere is knowledge,\nwhere is ignorance,\nwhere is bondage,\nwhere is freedom?" },
      { id: "18.62", number: "18.62", speaker: "Ashtavakra said:", text: "He for whom the supreme Self\nand the world are one,\nwhat can he renounce,\nwhat can he accept?" },
      { id: "18.63", number: "18.63", speaker: "Ashtavakra said:", text: "The yogi free of thought\nis neither engaged nor disengaged.\nHe neither knows meditation\nnor the lack of it." },
      { id: "18.64", number: "18.64", speaker: "Ashtavakra said:", text: "One whose firm conviction\nis \"I am the Infinite,\"\nwhat fear can touch him,\nwhat sorrow bind him?" },
      { id: "18.65", number: "18.65", speaker: "Ashtavakra said:", text: "Free of the idea of doing,\nfree of the idea of not-doing,\nfree of the three gunas,\nthe sage is established in Truth." },
      { id: "18.66", number: "18.66", speaker: "Ashtavakra said:", text: "The yogi in whom the mind\nhas dissolved into the Self\nneeds no support,\nno warning,\nno instruction." },
      { id: "18.67", number: "18.67", speaker: "Ashtavakra said:", text: "What lotus leaf floats on water\nand remains untouched—\nso does the wise one in the world." },
      { id: "18.68", number: "18.68", speaker: "Ashtavakra said:", text: "The jnani,\nfirm in the knowledge \"I am the Self,\"\nneeds neither the path nor a guide." },
      { id: "18.69", number: "18.69", speaker: "Ashtavakra said:", text: "The wise one,\nfree of the sense of doership,\nlives happily\nwithout becoming entangled." },
      { id: "18.70", number: "18.70", speaker: "Ashtavakra said:", text: "The yogi established in the Self\nrequires neither effort nor indolence.\nHe is forever content\nin his own nature." },
      { id: "18.71", number: "18.71", speaker: "Ashtavakra said:", text: "Beyond the three gunas,\nbeyond the three states,\nthe yogi freed from the knots of the heart\nabides in the Self." },
      { id: "18.72", number: "18.72", speaker: "Ashtavakra said:", text: "To the knower of Truth,\nwhere is the need for the disciplines,\nwhere the world,\nwhere liberation,\nwhere bondage?" },
      { id: "18.73", number: "18.73", speaker: "Ashtavakra said:", text: "The great soul,\nwho exists as the timeless Self,\nneither acts,\nnor knows that he acts." },
      { id: "18.74", number: "18.74", speaker: "Ashtavakra said:", text: "In the yogi established in the Self,\nthere is no mental conflict,\nno elation,\nno depression." },
      { id: "18.75", number: "18.75", speaker: "Ashtavakra said:", text: "The wise one,\nfree of the sense of \"I\" and \"mine,\"\nneeds no doctrine,\nno teacher,\nno scripture." },
      { id: "18.76", number: "18.76", speaker: "Ashtavakra said:", text: "One for whom the Self alone exists,\nall forms are unreal,\nall names are unreal." },
      { id: "18.77", number: "18.77", speaker: "Ashtavakra said:", text: "He whose mind does not dwell\non the past or the future,\nwho is free from concern,\nwho knows no fear—\nwho but he is at peace?" },
      { id: "18.78", number: "18.78", speaker: "Ashtavakra said:", text: "One in whom imagination\nhas ceased to function,\nwho has become empty and pure,\nlives blissfully in this world." },
      { id: "18.79", number: "18.79", speaker: "Ashtavakra said:", text: "The yogi,\nfree from the tyranny of the mind,\nenjoys the greatest bliss,\nfirm in the knowledge \"I am the Self.\"" },
      { id: "18.80", number: "18.80", speaker: "Ashtavakra said:", text: "The sage who has realized\nthe nature of the Self,\nneither restrains nor indulges the senses." },
      { id: "18.81", number: "18.81", speaker: "Ashtavakra said:", text: "Free of the notion of \"I am separate,\"\nthe wise one is neither occupied nor empty." },
      { id: "18.82", number: "18.82", speaker: "Ashtavakra said:", text: "Having seen that he is not the doer,\nthe wise one is neither pleased nor displeased\nwith the results of action." },
      { id: "18.83", number: "18.83", speaker: "Ashtavakra said:", text: "Knowing that the self-sense is false,\nthe yogi has no trace of fear\nor grief." },
      { id: "18.84", number: "18.84", speaker: "Ashtavakra said:", text: "The mind of the yogi,\nfree from all notions of doership,\nis clear and transparent." },
      { id: "18.85", number: "18.85", speaker: "Ashtavakra said:", text: "One whose understanding is clear,\nwhose mind is unfettered,\nwhose vision is pure,\nis free in this world." },
      { id: "18.86", number: "18.86", speaker: "Ashtavakra said:", text: "The wise one,\nfree from the sense of doership,\nneeds neither scripture nor teacher." },
      { id: "18.87", number: "18.87", speaker: "Ashtavakra said:", text: "By recognizing the emptiness of the mind,\nby understanding that all is the Self,\nthe yogi becomes free." },
      { id: "18.88", number: "18.88", speaker: "Ashtavakra said:", text: "The yogi who sees the universe\nas nothing but imagination\nis already liberated." },
      { id: "18.89", number: "18.89", speaker: "Ashtavakra said:", text: "Having transcended the three gunas,\nfree from ego,\nfull of bliss,\nthe yogi dwells in the Self." },
      { id: "18.90", number: "18.90", speaker: "Ashtavakra said:", text: "One in whom all desires have perished,\nwho has forgotten himself,\nwho dwells in the Self—\nhe is truly blissful." },
      { id: "18.91", number: "18.91", speaker: "Ashtavakra said:", text: "The jnani,\nfree of illusion and delusion,\nneeds neither effort nor rest." },
      { id: "18.92", number: "18.92", speaker: "Ashtavakra said:", text: "One established in the knowledge\n\"I am the Infinite,\"\nwhat bondage can touch him,\nwhat freedom concern him?" },
      { id: "18.93", number: "18.93", speaker: "Ashtavakra said:", text: "The wise one,\nfree from the sense of \"I\" in action,\nneeds no guide for the path." },
      { id: "18.94", number: "18.94", speaker: "Ashtavakra said:", text: "Through knowledge of the Self,\nthrough detachment from illusion,\nthe yogi becomes immaculate." },
      { id: "18.95", number: "18.95", speaker: "Ashtavakra said:", text: "For him who realizes \"There is no doer,\"\nwhat good,\nwhat bad,\nwhat loss,\nwhat gain?" },
      { id: "18.96", number: "18.96", speaker: "Ashtavakra said:", text: "The yogi whose mind is without movement,\nwhose understanding is clear,\nwhose knowledge is firm,\nis already free." },
      { id: "18.97", number: "18.97", speaker: "Ashtavakra said:", text: "One immersed in the Self,\nfree from action,\nfree from bondage,\nis the true knower." },
      { id: "18.98", number: "18.98", speaker: "Ashtavakra said:", text: "Having abandoned all distinction,\nall discrimination,\nthe yogi dwells blissfully in the Self." },
      { id: "18.99", number: "18.99", speaker: "Ashtavakra said:", text: "One who has transcended the mind,\nwho has gone beyond time,\nwho is established in the Truth,\nneeds no instruction." },
      { id: "18.100", number: "18.100", speaker: "Ashtavakra said:", text: "The sage who knows the Truth,\nwho is free from delusion,\nwho is blissful in his nature,\nis the Eternal Self." },
    ]
  },
  {
    id: 19,
    title: "Adoration",
    verses: [
      { id: "19.1", number: "19.1", speaker: "Janaka said:", text: "Praise to That which is\nthe Witness of all conditions,\nwhich is Being, Consciousness, Bliss,\nwithout equal, changeless, eternal." },
      { id: "19.2", number: "19.2", speaker: "Janaka said:", text: "Praise to That\nwhose very nature is Bliss,\nwhose knowledge shines\nlike a lamp in the heart." },
      { id: "19.3", number: "19.3", speaker: "Janaka said:", text: "Praise to That\nwhich gives life to all beings,\nwhich reveals Itself as the universe\nand yet remains untouched." },
      { id: "19.4", number: "19.4", speaker: "Janaka said:", text: "Praise to That\nwhose nature cannot be known by the mind,\nwhose reality transcends all concepts." },
      { id: "19.5", number: "19.5", speaker: "Janaka said:", text: "Praise to the Self Eternal,\nwhose light alone illuminates\nall that appears." },
    ]
  },
  {
    id: 20,
    title: "Final Questions",
    verses: [
      { id: "20.1", number: "20.1", speaker: "Janaka said:", text: "Master, what am I?\nWhat is this universe?\nWhat is the mind?\nWhat is liberation?" },
      { id: "20.2", number: "20.2", speaker: "Ashtavakra said:", text: "You are that Self\nof which the universe and mind\nare but imaginary appearances.\nThere is no bondage,\nno liberation." },
      { id: "20.3", number: "20.3", speaker: "Janaka said:", text: "Master, what is knowledge?\nWhat is ignorance?\nWhat is becoming?\nWhat is dissolution?" },
      { id: "20.4", number: "20.4", speaker: "Ashtavakra said:", text: "All are but thought-constructs\nin the Self.\nIn Reality,\nthere is neither becoming nor dissolution." },
      { id: "20.5", number: "20.5", speaker: "Janaka said:", text: "Master, who is bound?\nWho is free?\nWho practices?\nWho is realized?" },
      { id: "20.6", number: "20.6", speaker: "Ashtavakra said:", text: "These too are imaginations.\nThere is no bondage,\nno freedom,\nno practice,\nno realization.\nAll is but the Self." },
    ]
  },
];
